# Goal
geometry_msgs/PoseStamped[] waypoints  # Lista de waypoints para o drone seguir

---
# Result
bool success  # Indicação se todos os waypoints foram alcançados com sucesso

---
# Feedback
geometry_msgs/PoseStamped current_pose  # Posição atual enquanto navega pelos waypoints
