base_controller:
  ros__parameters:
    services:
      arming: "/mavros/cmd/arming"
      takeoff: "/mavros/cmd/takeoff"
      setmode: "/mavros/set_mode"
      land: "/mavros/cmd/land"
      stream_rate: "/mavros/set_stream_rate"
    publishers:
      setpoint_position_local: "/mavros/setpoint_position/local"
    subscribers:
      state: "/mavros/state"
      rangefinder: "/mavros/rangefinder/rangefinder"
      local_position_pose: "/mavros/local_position/pose"
    custom_modes:
      - "STABILIZE"
      - "ACRO"
      - "ALT_HOLD"
      - "AUTO"
      - "GUIDED"
      - "LOITER"
      - "RTL"
      - "CIRCLE"
      - "POSITION"
      - "LAND"
      - "OF_LOITER"
      - "DRIFT"
      - "SPORT"
      - "FLIP"
      - "AUTOTUNE"
      - "POSHOLD"
      - "BRAKE"
      - "THROW"
      - "AVOID_ADSB"
      - "GUIDED_NOGPS"
